### ISSUE TITLE
Make the "Sharing:" text settable

### ISSUE THREAD

**Issue by mswartz** [Upstatement/quickshare#11]
People might want to configure the text that pops up in your share window. Right now the "Sharing:" text appears to be hardcoded, would be nice to pass this to quickshare() as a param.

**Comment by jarednova** [comment]
@mswartz I'm going to take a look at this for now. I recall @thetmkay making that adjustable so I want to check the docs first to see if it's just a documentation oversight

**Comment by thetmkay** [comment]
Apologies for the delay, @mswartz have you tried adding the `data-qs-tweet-body` attribute?

See https://github.com/Upstatement/quickshare/wiki/Service-Attributes-Reference#tweet-body

**Comment by mswartz** [comment]
@thetmkay I have not! That looks like what I was looking for. To be honest i've only used quickshare for a few minutes. Will give it a try. Thanks!
