### ISSUE TITLE
Resolve Missing Icons

### ISSUE THREAD

**Issue by jarednova** [Upstatement/quickshare#13]
On the [examples branch](https://github.com/Upstatement/quickshare/tree/examples), icons are not displaying in the `qs_demo.html` file.

- [x] Through modification of the markup or JS get them to appear
- [x] Document how to make icons appear if it differs from the [current documentation](https://github.com/Upstatement/quickshare/tree/examples#icons)

**Comment by rkrishnan8594** [comment]
Resolved by adding `http:` in front of the font-awesome stylesheet href that supplies the icons.
