### ISSUE TITLE
Twitter widgets conflict?

### ISSUE THREAD

**Issue by yuvilio** [Upstatement/quickshare#19]
Noticed that for a site that uses twitters widget.js , the share functionality doesn't seem to work? (clicking on the link ).  I've used this before and it works great. 

Then tried it on a site that had this snippet, used to show twitter widgets like timelines, 

```javascript
<script src="//platform.twitter.com/widgets.js" async></script>
```

and the twitter clicking the twitter quickshare links didn't do anything.

Using version 1.3.4 .

**Comment by emmagard** [comment]
@yuvilio Thanks for filing this issue. I'm taking a look at this problem this week.

**Comment by yuvilio** [comment]
Sweet. Thanks, @emmagard. If it's reproducible and addressable, I'm happy to retest.

**Comment by emmagard** [comment]
@yuvilio This has been resolved with the last PR. Let me know if you are still experiencing any other conflicts. Thanks again for pointing out this issue.

**Comment by yuvilio** [comment]
Nice.  I just tried it with quickshare 1.3.6 and the twitter share button now works, even with the ```widgets.js``` library there.  Thanks @emmagard !
