### ISSUE TITLE
Twitter link doesn't work on particular story

### ISSUE THREAD

**Issue by jarednova** [Upstatement/quickshare#26]
On this particular page:

http://www.thetrace.org/2015/11/metro-homicide-reporters-crime-scene/

... the Twitter link doesn't work. No JS error is fired. I've verified that other Twitter links on this site DO work as do the Facebook and Email links on the page. The only thing I can think of is whether the Periods. In. The. Headline. might affect something in the Twitter share code

**Comment by emmagard** [comment]
@jarednova This has to do with the embedded tweets in the article. I am going to figure out a fix for this.

**Comment by jarednova** [comment]
awesome! glad we figured out the source of the problem at least

**Comment by emmagard** [comment]
@jarednova I updated quickshare on my local version of the trace website and that seemed to fix the issue. Should I do this and push up to a branch or master?

**Comment by jarednova** [comment]
I'm already working w them on a deployment thing, so we're all set -- thanks for taking a look!
